// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksfctvcevtukczvfieoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzZmN0dmNldnR1a2N6dmZpZW95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTE2OTEsImV4cCI6MjA2Mzk4NzY5MX0.QrCVkW8pZPKwmhIkdoUMK7sfX_6p5GUqkJQYWzxnrQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);